version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Moscow"
      time: "00:00"
    pull-request-branch-name:
      separator: "-"